import nltk

# form index files are fixed width formated.  Character positions of relevent
# fields
NAME_POS = (12, 74)
CIK_POS = (74, 86)
DATE_POS = (86, 98)
PATH_POS = (98, None)


# short term debt signifiers.  See reference:
# http://www.xbrlsite.com/2014/Protototype/Classes/
# currentLiabilities_Tree.html

SHORT_TERM_GAAP = [
    "LOANSPAYABLETOBANKCURRENT",
    "OTHERLOANSPAYABLECURRENT",
    "MEDIUMTERMNOTESCURRENT",
    "CONVERTIBLENOTESPAYABLECURRENT",
    "NOTESPAYABLETOBANKCURRENT",
    "SENIORNOTESCURRENT",
    "JUNIORSUBORDINATEDNOTESCURRENT",
    "OTHERNOTESPAYABLECURRENT",
    "LOANSPAYABLECURRENT",
    "NOTESPAYABLECURRENT",
    "SECUREDDEBTCURRENT",
    "CONVERTIBLEDEBTCURRENT",
    "UNSECUREDDEBTCURRENT",
    "SUBORDINATEDDEBTCURRENT",
    "CONVERTIBLESUBORDINATEDDEBTCURRENT",
    "LONGTERMCOMMERCIALPAPERCURRENT",
    "LONGTERMCONSTRUCTIONLOANCURRENT",
    "LONGTERMTRANSITIONBONDCURRENT",
    "LONGTERMPOLLUTIONCONTROLBONDCURRENT",
    "OTHERLONGTERMDEBTCURRENT",
    "LINESOFCREDITCURRENT",
    "NOTESANDLOANSPAYABLECURRENT",
    "LONGTERMDEBTCURRENT",
    "CAPITALLEASEOBLIGATIONSCURRENT",
    "BANKOVERDRAFTS",
    "COMMERCIALPAPER",
    "BRIDGELOAN",
    "CONSTRUCTIONLOAN",
    "SHORTTERMBANKLOANSANDNOTESPAYABLE",
    "SHORTTERMNONBANKLOANSANDNOTESPAYABLE",
    "SECURITIESSOLDUNDERAGREEMENTSTOREPURCHASE",
    "WAREHOUSEAGREEMENTBORROWINGS",
    "OTHERSHORTTERMBORROWINGS",
    "DEBTCURRENT",
    "LONGTERMDEBTANDCAPITALLEASEOBLIGATIONSCURRENT",
    "SHORTTERMBORROWINGS",
    "LIABILITIESCURRENT",
    "ACCOUNTSPAYABLEANDACCRUEDLIABILITIESCURRENT",
    "ACCOUNTSPAYABLECURRENT",
    "ACCOUNTSPAYABLETRADECURRENT",
    "ACCOUNTSPAYABLEOTHERCURRENT",
    "ACCRUEDLIABILITIESCURRENT",
    "OTHERACCRUEDLIABILITIESCURRENT",
    "ACCOUNTSPAYABLERELATEDPARTIESCURRENT",
    "OTHERLIABILITIESCURRENT"
]

# Long term debt signifiers.  See reference:
# http://www.xbrlsite.com/2014/Protototype/Classes/
# currentLiabilities_Tree.html

LONG_TERM_GAAP = [
    "LONGTERMNOTESPAYABLE",
    "OTHERLONGTERMNOTESPAYABLE",
    "NOTESPAYABLETOBANKNONCURRENT",
    "CONVERTIBLELONGTERMNOTESPAYABLE",
    "SENIORLONGTERMNOTES",
    "JUNIORSUBORDINATEDLONGTERMNOTES",
    "OTHERLOANSPAYABLELONGTERM",
    "LONGTERMLOANSFROMBANK",
    "LONGTERMNOTESANDLOANS",
    "LONGTERMLOANSPAYABLE",
    "LONGTERMDEBTNONCURRENT",
    "OTHERLONGTERMDEBTNONCURRENT",
    "LONGTERMPOLLUTIONCONTROLBOND",
    "LONGTERMTRANSITIONBOND",
    "CONVERTIBLESUBORDINATEDDEBTNONCURRENT",
    "CONVERTIBLEDEBTNONCURRENT",
    "UNSECUREDLONGTERMDEBT",
    "SUBORDINATEDLONGTERMDEBT",
    "SECUREDLONGTERMDEBT",
    "CONSTRUCTIONLOANNONCURRENT",
    "COMMERCIALPAPERNONCURRENT",
    "LONGTERMLINEOFCREDIT",
    "CAPITALLEASEOBLIGATIONSNONCURRENT",
    "LONGTERMDEBTANDCAPITALLEASEOBLIGATIONS",
    "LIABILITIESOTHERTHANLONGTERMDEBTNONCURRENT",
    "LIABILITIESNONCURRENT"
]

# mapping between common phrase extracted during HTML / Text processing
# and gaap standard terminology

RAW_TO_GAAP = {

    'ACCOUNTS PAYABLE':
        'ACCOUNTSPAYABLECURRENT',

    'ACCOUNTS PAYABLE ACCRUED EXPENSES AND OTHER LIABILITIES':
        'ACCOUNTSPAYABLEANDACCRUEDLIABILITIESCURRENT',

    'ACCOUNTS PAYABLE ACCRUED LIABILITIES AND DEFERRED REVENUE':
        'ACCRUEDLIABILITIESCURRENT',

    'ACCOUNTS PAYABLE AFFILIATED COMPANIES':
        'ACCOUNTSPAYABLERELATEDPARTIESCURRENT',

    'ACCOUNTS PAYABLE AFFILIATES':
        'ACCOUNTSPAYABLERELATEDPARTIESCURRENT',

    'ACCOUNTS PAYABLE AND ACCRUALS':
        'ACCOUNTSPAYABLEANDACCRUEDLIABILITIESCURRENT',

    'ACCOUNTS PAYABLE AND ACCRUED EXPENSES':
        'ACCOUNTSPAYABLEANDACCRUEDLIABILITIESCURRENT',

    'ACCOUNTS PAYABLE AND ACCRUED LIABILITIES':
        'ACCOUNTSPAYABLEANDACCRUEDLIABILITIESCURRENT',

    'ACCOUNTS PAYABLE AND OTHER':
        'ACCOUNTSPAYABLEANDACCRUEDLIABILITIESCURRENT',

    'ACCOUNTS PAYABLE AND OTHER ACCRUED LIABILITIES':
        'ACCOUNTSPAYABLEANDACCRUEDLIABILITIESCURRENT',

    'ACCOUNTS PAYABLE AND OTHER CURRENT LIABILITIES':
        'ACCOUNTSPAYABLEANDACCRUEDLIABILITIESCURRENT',

    'ACCOUNTS PAYABLE AND OTHER LIABILITIES':
        'ACCOUNTSPAYABLEANDACCRUEDLIABILITIESCURRENT',

    'ACCOUNTS PAYABLE FOR GRAIN':
        'OTHERLIABILITIESCURRENT',

    'ACCOUNTS PAYABLE PARENT AND AFFILIATES':
        'ACCOUNTSPAYABLECURRENT',

    'ACCOUNTS PAYABLE PRINCIPALLY TRADE':
        'ACCOUNTSPAYABLETRADECURRENT',

    'ACCOUNTS PAYABLE RELATED PARTIES':
        'ACCOUNTSPAYABLERELATEDPARTIESCURRENT',

    'ACCOUNTS PAYABLE TO AFFILIATED COMPANIES':
        'ACCOUNTSPAYABLERELATEDPARTIESCURRENT',

    'ACCOUNTS PAYABLE TO AFFILIATES':
        'ACCOUNTSPAYABLERELATEDPARTIESCURRENT',

    'ACCOUNTS PAYABLE TO ASSOCIATED COMPANIES':
        'ACCOUNTSPAYABLERELATEDPARTIESCURRENT',

    'ACCOUNTS PAYABLE TRADE':
        'ACCOUNTSPAYABLETRADECURRENT',

    'ACCOUNTS PAYABLE TRADE CREDITORS':
        'ACCOUNTSPAYABLETRADECURRENT',

    'ACCRUALS AND OTHER CURRENT LIABILITIES':
        'ACCRUEDLIABILITIESCURRENT',

    'ACCRUED AND OTHER CURRENT LIABILITIES':
        'LIABILITIESCURRENT',

    'ACCRUED EXPENSES AND OTHER CURRENT LIABILITIES':
        'OTHERACCRUEDLIABILITIESCURRENT',

    'ACCRUED EXPENSES AND OTHER LIABILITIES':
        'OTHERLIABILITIESCURRENT',

    'ACCRUED LIABILITIES':
        'ACCRUEDLIABILITIESCURRENT',

    'ACCRUED LIABILITIES AFFILIATE':
        'OTHERLIABILITIESCURRENT',

    'ACCRUED LIABILITIES AND EXPENSES':
        'ACCRUEDLIABILITIESCURRENT',

    'ACCRUED LIABILITIES AND INCOME TAXES':
        'ACCRUEDLIABILITIESCURRENT',

    'ACCRUED LIABILITIES AND OTHER':
        'ACCRUEDLIABILITIESCURRENT',

    'ACCRUED LIABILITIES AND OTHER PAYABLES':
        'ACCOUNTSPAYABLEANDACCRUEDLIABILITIESCURRENT',

    'ACCRUED LIABILITIES OTHER':
        'OTHERACCRUEDLIABILITIESCURRENT',

    'ACCRUED LIABILITIES SALARIES AND WAGES':
        'OTHERLIABILITIESCURRENT',

    'ACCRUED PAYROLL AND RELATED LIABILITIES':
        'OTHERACCRUEDLIABILITIESCURRENT',

    'ADDITION TO SHORT TERM BORROWINGS':
        'OTHERSHORTTERMBORROWINGS',

    'AND ACCRUED LIABILITIES':
        'ACCRUEDLIABILITIESCURRENT',

    'CAPITAL LEASE OBLIGATIONS':
        'CAPITALLEASEOBLIGATIONSNONCURRENT',

    'CAPITAL LEASE OBLIGATIONS DUE WITHIN ONE YEAR':
        'CAPITALLEASEOBLIGATIONSCURRENT',

    'CAPITAL LEASE OBLIGATIONS LESS CURRENT PORTION':
        'CAPITALLEASEOBLIGATIONSNONCURRENT',

    'CAPITAL LEASE OBLIGATIONS NET OF CURRENT MATURITIES':
        'CAPITALLEASEOBLIGATIONSNONCURRENT',

    'CAPITALIZED LEASE OBLIGATIONS':
        'CAPITALLEASEOBLIGATIONSNONCURRENT',

    'COMMERCIAL PAPER AND OTHER SHORT TERM BORROWINGS':
        'SHORTTERMBORROWINGS',

    'CONSTRUCTION AND OTHER SHORT TERM LOANS':
        'OTHERLOANSPAYABLECURRENT',

    'CURRENT DEBT':
        'DEBTCURRENT',

    'CURRENT DEBT MATURITIES':
        'DEBTCURRENT',

    'CURRENT INSTALLMENTS OF CAPITAL LEASE OBLIGATIONS':
        'CAPITALLEASEOBLIGATIONSCURRENT',

    'CURRENT INSTALLMENTS OF LONG TERM DEBT':
        'LONGTERMDEBTCURRENT',

    'CURRENT INSTALLMENTS OF OBLIGATIONS UNDER CAPITAL LEASES':
        'CAPITALLEASEOBLIGATIONSCURRENT',

    'CURRENT LIABILITIES':
        'LIABILITIESCURRENT',

    'CURRENT LIABILITIES ACCOUNTS AND NOTES PAYABLE':
        'ACCOUNTSPAYABLECURRENT',

    'CURRENT LIABILITIES ACCOUNTS PAYABLE':
        'ACCOUNTSPAYABLECURRENT',

    'CURRENT LIABILITIES ACCOUNTS PAYABLE AND ACCRUED EXPENSES':
        'ACCOUNTSPAYABLEANDACCRUEDLIABILITIESCURRENT',

    'CURRENT LIABILITIES ACCOUNTS PAYABLE TRADE':
        'ACCOUNTSPAYABLETRADECURRENT',

    'CURRENT LIABILITIES BANK BORROWINGS':
        'SHORTTERMBANKLOANSANDNOTESPAYABLE',

    'CURRENT LIABILITIES BANK LOANS':
        'SHORTTERMBANKLOANSANDNOTESPAYABLE',

    'CURRENT LIABILITIES BANK OVERDRAFT':
        'BANKOVERDRAFTS',

    'CURRENT LIABILITIES COMMERCIAL PAPER':
        'COMMERCIALPAPER',

    'CURRENT LIABILITIES CURRENT INSTALLMENTS OF LONG TERM DEBT':
        'LONGTERMDEBTCURRENT',

    'CURRENT LIABILITIES CURRENT MATURITIES OF LONG TERM DEBT':
        'LONGTERMDEBTCURRENT',

    'CURRENT LIABILITIES CURRENT PORTION OF LONG DEBT':
        'LONGTERMDEBTCURRENT',

    'CURRENT LIABILITIES CURRENT PORTION OF LONG TERM DEBT':
        'LONGTERMDEBTCURRENT',

    'CURRENT LIABILITIES CURRENT PORTION OF LONG TERM DEBT AND CAPITAL LEASES':
        'LONGTERMDEBTANDCAPITALLEASEOBLIGATIONSCURRENT',

    'CURRENT LIABILITIES CURRENT PORTION OF LONG TERM OBLIGATIONS':
        'LONGTERMDEBTCURRENT',

    'CURRENT LIABILITIES CURRENT PORTION OF NOTES PAYABLE':
        'NOTESPAYABLECURRENT',

    'CURRENT LIABILITIES CURRENTLY MATURING LONG TERM DEBT':
        'LONGTERMDEBTCURRENT',

    'CURRENT LIABILITIES DEBT DUE WITHIN ONE YEAR':
        'DEBTCURRENT',

    'CURRENT LIABILITIES DEBT MATURING WITHIN ONE YEAR':
        'DEBTCURRENT',

    'CURRENT LIABILITIES LINE OF CREDIT':
        'LINESOFCREDITCURRENT',

    'CURRENT LIABILITIES LINES OF CREDIT':
        'LINESOFCREDITCURRENT',

    'CURRENT LIABILITIES LOANS PAYABLE':
        'LOANSPAYABLECURRENT',

    'CURRENT LIABILITIES LONG TERM DEBT DUE WITHIN ONE YEAR':
        'LONGTERMDEBTCURRENT',

    'CURRENT LIABILITIES LONG TERM DEBT DUE WITHIN TWELVE MONTHS':
        'LONGTERMDEBTCURRENT',

    'CURRENT LIABILITIES NOTE PAYABLE':
        'NOTESPAYABLECURRENT',

    'CURRENT LIABILITIES NOTES AND ACCEPTANCES PAYABLE':
        'NOTESPAYABLECURRENT',

    'CURRENT LIABILITIES NOTES AND LOANS PAYABLE':
        'NOTESANDLOANSPAYABLECURRENT',

    'CURRENT LIABILITIES NOTES PAYABLE':
        'NOTESPAYABLECURRENT',

    'CURRENT LIABILITIES NOTES PAYABLE AND CURRENT PORTION OF LONG TERM DEBT':
        'DEBTCURRENT',

    'CURRENT LIABILITIES NOTES PAYABLE BANK':
        'NOTESPAYABLETOBANKCURRENT',

    'CURRENT LIABILITIES NOTES PAYABLE BANKS':
        'NOTESPAYABLETOBANKCURRENT',

    'CURRENT LIABILITIES NOTES PAYABLE TO BANK':
        'NOTESPAYABLETOBANKCURRENT',

    'CURRENT LIABILITIES NOTES PAYABLE TO BANKS':
        'NOTESPAYABLETOBANKCURRENT',

    'CURRENT LIABILITIES OF DISCONTINUED OPERATIONS':
        'OTHERACCRUEDLIABILITIESCURRENT',

    'CURRENT LIABILITIES REVOLVING CREDIT FACILITY':
        'LINESOFCREDITCURRENT',

    'CURRENT LIABILITIES REVOLVING LINE OF CREDIT':
        'LINESOFCREDITCURRENT',

    'CURRENT LIABILITIES SHORT TERM BORROWINGS':
        'SHORTTERMBORROWINGS',

    'CURRENT LIABILITIES SHORT TERM DEBT':
        'SHORTTERMBORROWINGS',

    'CURRENT LIABILITIES SHORT TERM DEBT INCLUDING CURRENT MATURITIES':
        'SHORTTERMBORROWINGS',

    'CURRENT LIABILITIES TRADE ACCOUNTS PAYABLE':
        'ACCOUNTSPAYABLETRADECURRENT',

    'CURRENT LIABILITIES TRADE PAYABLES':
        'ACCOUNTSPAYABLETRADECURRENT',

    'CURRENT LIABILITIESACCOUNTS PAYABLE':
        'ACCOUNTSPAYABLECURRENT',

    'CURRENT MATURITIES OF CAPITALIZED LEASE OBLIGATIONS':
        'CAPITALLEASEOBLIGATIONSCURRENT',

    'CURRENT MATURITIES OF LONG TERM DEBT':
        'LONGTERMDEBTCURRENT',

    'CURRENT MATURITIES OF LONG TERM DEBT AND CAPITAL LEASE OBLIGATIONS':
        'LONGTERMDEBTANDCAPITALLEASEOBLIGATIONSCURRENT',

    'CURRENT MATURITIES OF LONG TERM DEBT AND OBLIGATIONS UNDER CAPITAL LEASE':
        'LONGTERMDEBTANDCAPITALLEASEOBLIGATIONSCURRENT',

    'CURRENT MATURITIES OF NOTES PAYABLE':
        'NOTESPAYABLECURRENT',

    'CURRENT OBLIGATIONS UNDER CAPITAL LEASES':
        'CAPITALLEASEOBLIGATIONSCURRENT',

    'CURRENT PORTION OF CAPITAL LEASE OBLIGATIONS':
        'CAPITALLEASEOBLIGATIONSCURRENT',

    'CURRENT PORTION OF DEBT':
        'DEBTCURRENT',

    'CURRENT PORTION OF LEASE OBLIGATIONS':
        'CAPITALLEASEOBLIGATIONSCURRENT',

    'CURRENT PORTION OF LOANS PAYABLE':
        'LOANSPAYABLECURRENT',

    'CURRENT PORTION OF LONG TERM DEBT':
        'LONGTERMDEBTCURRENT',

    'CURRENT PORTION OF LONG TERM DEBT AND CAPITAL LEASE OBLIGATIONS':
        'LONGTERMDEBTANDCAPITALLEASEOBLIGATIONSCURRENT',

    'CURRENT PORTION OF LONG TERM DEBT AND SHORT TERM BORROWINGS':
        'DEBTCURRENT',

    'CURRENT PORTION OF NOTES PAYABLE':
        'NOTESPAYABLECURRENT',

    'CURRENT PORTION OF OBLIGATIONS UNDER CAPITAL LEASES':
        'CAPITALLEASEOBLIGATIONSCURRENT',

    'LIABILITIES ACCOUNTS PAYABLE':
        'ACCOUNTSPAYABLECURRENT',

    'LIABILITIES ACCOUNTS PAYABLE TO AFFILIATES':
        'ACCOUNTSPAYABLERELATEDPARTIESCURRENT',

    'LIABILITIES SHORT TERM DEBT':
        'SHORTTERMBORROWINGS',

    'LOANS PAYABLE SHORT TERM COMMERCIAL PAPER':
        'COMMERCIALPAPER',

    'LONG TERM BANK LOANS':
        'LONGTERMLOANSFROMBANK',

    'LONG TERM BORROWINGS':
        'LONGTERMLOANSPAYABLE',

    'LONG TERM DEBT':
        'LONGTERMDEBTNONCURRENT',

    'LONG TERM DEBT AND AND OTHER BORROWINGS':
        'LONGTERMDEBTNONCURRENT',

    'LONG TERM DEBT AND CAPITAL LEASE OBLIGATIONS':
        'LONGTERMDEBTANDCAPITALLEASEOBLIGATIONS',

    'LONG TERM DEBT AND CAPITAL LEASES':
        'LONGTERMDEBTANDCAPITALLEASEOBLIGATIONS',

    'LONG TERM DEBT AND CAPITAL LEASES LESS CURRENT MATURITIES':
        'LONGTERMDEBTANDCAPITALLEASEOBLIGATIONS',

    'LONG TERM DEBT AND CAPITALIZED LEASE OBLIGATIONS':
        'LONGTERMDEBTANDCAPITALLEASEOBLIGATIONS',

    'LONG TERM DEBT AND OBLIGATIONS UNDER CAPITAL LEASES':
        'LONGTERMDEBTANDCAPITALLEASEOBLIGATIONS',

    'LONG TERM DEBT CURRENT PORTION':
        'LONGTERMDEBTCURRENT',

    'LONG TERM DEBT DEBENTURES':
        'OTHERLONGTERMDEBTNONCURRENT',

    'LONG TERM DEBT DUE AFTER ONE YEAR':
        'LONGTERMDEBTNONCURRENT',

    'LONG TERM DEBT DUE CURRENTLY':
        'LONGTERMDEBTCURRENT',

    'LONG TERM DEBT DUE WITHIN ONE YEAR':
        'LONGTERMDEBTCURRENT',

    'LONG TERM DEBT EXCLUDING CURRENT INSTALLMENTS':
        'LONGTERMDEBTNONCURRENT',

    'LONG TERM DEBT EXCLUDING CURRENT MATURITIES':
        'LONGTERMDEBTNONCURRENT',

    'LONG TERM DEBT EXCLUDING CURRENT PORTION':
        'LONGTERMDEBTNONCURRENT',

    'LONG TERM DEBT LESS CURRENT INSTALLMENTS':
        'LONGTERMDEBTNONCURRENT',

    'LONG TERM DEBT LESS CURRENT MATURITIES':
        'LONGTERMDEBTNONCURRENT',

    'LONG TERM DEBT LESS CURRENT PORTION':
        'LONGTERMDEBTNONCURRENT',

    'LONG TERM DEBT NET':
        'LONGTERMDEBTNONCURRENT',

    'LONG TERM DEBT NET OF AMOUNT DUE WITHIN ONE YEAR':
        'LONGTERMDEBTNONCURRENT',

    'LONG TERM DEBT NET OF CURRENT MATURITIES':
        'LONGTERMDEBTNONCURRENT',

    'LONG TERM DEBT NET OF CURRENT PORTION':
        'LONGTERMDEBTNONCURRENT',

    'LONG TERM DEBT NOTES PAYABLE':
        'LONGTERMNOTESPAYABLE',

    'LONG TERM DEBT OBLIGATIONS':
        'LONGTERMDEBTNONCURRENT',

    'LONG TERM LIABILITIES':
        'LIABILITIESNONCURRENT',

    'LONG TERM LIABILITIES LESS CURRENT MATURITIES':
        'LIABILITIESNONCURRENT',

    'LONG TERM LIABILITIES LONG TERM DEBT':
        'LIABILITIESNONCURRENT',

    'LONG TERM LIABILITIES NOTES PAYABLE':
        'LONGTERMNOTESPAYABLE',

    'LONG TERM LOANS':
        'LONGTERMLOANSPAYABLE',

    'LONG TERM NOTES':
        'LONGTERMNOTESPAYABLE',

    'LONG TERM NOTES PAYABLE':
        'LONGTERMNOTESPAYABLE',

    'LONG TERM OBLIGATIONS UNDER CAPITAL LEASES':
        'CAPITALLEASEOBLIGATIONSNONCURRENT',

    'LONG TERM PORTION OF CAPITAL LEASE OBLIGATIONS':
        'CAPITALLEASEOBLIGATIONSNONCURRENT',

    'LONG TERM PORTION OF NOTES PAYABLE':
        'NOTESPAYABLECURRENT',

    'NONCURRENT LIABILITIES LONG TERM DEBT':
        'LONGTERMDEBTNONCURRENT',

    'NOTE PAYABLE AND CURRENT MATURITIES OF LONG TERM DEBT OBLIGATIONS':
        'SHORTTERMBORROWINGS',

    'NOTES PAYABLE AND CURRENT MATURITIES OF LONG TERM DEBT':
        'LONGTERMDEBTCURRENT',

    'NOTES PAYABLE AND CURRENT PORTION OF LONG TERM DEBT':
        'LONGTERMDEBTCURRENT',

    'NOTES PAYABLE CAPITALIZED LEASES AND OTHER LONG TERM DEBT':
        'LONGTERMDEBTANDCAPITALLEASEOBLIGATIONS',

    'OBLIGATIONS UNDER CAPITAL LEASES':
        'CAPITALLEASEOBLIGATIONSNONCURRENT',

    'OBLIGATIONS UNDER CAPITAL LEASES EXCLUDING CURRENT INSTALLMENTS':
        'CAPITALLEASEOBLIGATIONSNONCURRENT',

    'OTHER ACCOUNTS PAYABLE':
        'ACCOUNTSPAYABLEOTHERCURRENT',

    'OTHER ACCRUED LIABILITIES':
        'OTHERACCRUEDLIABILITIESCURRENT',

    'OTHER CURRENT LIABILITIES':
        'OTHERACCRUEDLIABILITIESCURRENT',

    'OTHER LIABILITIES LONG TERM DEBT':
        'OTHERLONGTERMDEBTNONCURRENT',

    'OTHER LONG TERM DEBT':
        'OTHERLONGTERMDEBTNONCURRENT',

    'OTHER LONG TERM LIABILITIES':
        'LIABILITIESOTHERTHANLONGTERMDEBTNONCURRENT',

    'OTHER LONG TERM LIABILITIES AND DEFERRED CREDITS':
        'OTHERLIABILITIESCURRENT',

    'OTHER NON CURRENT LIABILITIES':
        'LIABILITIESOTHERTHANLONGTERMDEBTNONCURRENT',

    'OTHER NONCURRENT LIABILITIES':
        'LIABILITIESOTHERTHANLONGTERMDEBTNONCURRENT',

    'OTHER NONCURRENT LIABILITIES NUCLEAR FUEL LEASE OBLIGATIONS':
        'LIABILITIESOTHERTHANLONGTERMDEBTNONCURRENT',

    'OTHER NONCURRENT LIABILITIES OBLIGATIONS UNDER CAPITAL LEASES':
        'CAPITALLEASEOBLIGATIONSNONCURRENT',

    'OTHER SHORT TERM BORROWINGS':
        'OTHERSHORTTERMBORROWINGS',

    'OTHER SHORT TERM DEBT':
        'OTHERSHORTTERMBORROWINGS',

    'PAYABLES AND ACCRUED LIABILITIES':
        'ACCOUNTSPAYABLEANDACCRUEDLIABILITIESCURRENT',

    'PAYMENT OF CAPITAL LEASE OBLIGATIONS':
        'CAPITALLEASEOBLIGATIONSCURRENT',

    'PAYMENTS OF LONG TERM DEBT':
        'LONGTERMDEBTCURRENT',

    'PAYMENTS ON CAPITALIZED LEASE OBLIGATIONS':
        'CAPITALLEASEOBLIGATIONSCURRENT',

    'PAYMENTS ON LONG TERM BORROWINGS':
        'LONGTERMDEBTCURRENT',

    'PAYMENTS ON LONG TERM DEBT':
        'LONGTERMDEBTCURRENT',

    'PRINCIPAL PAYMENTS OF LONG TERM DEBT':
        'LONGTERMDEBTCURRENT',

    'PRINCIPAL PAYMENTS ON CAPITAL LEASE OBLIGATIONS':
        'CAPITALLEASEOBLIGATIONSCURRENT',

    'PRINCIPAL PAYMENTS ON LONG TERM DEBT':
        'LONGTERMDEBTCURRENT',

    'PRINCIPAL PAYMENTS ON LONG TERM DEBT AND CAPITAL LEASE OBLIGATIONS':
        'LONGTERMDEBTANDCAPITALLEASEOBLIGATIONSCURRENT',

    'SENIOR LONG TERM DEBT':
        'SENIORLONGTERMNOTES',

    'SHORT TERM BANK BORROWINGS':
        'SHORTTERMBANKLOANSANDNOTESPAYABLE',

    'SHORT TERM BANK DEBT':
        'SHORTTERMBANKLOANSANDNOTESPAYABLE',

    'SHORT TERM BANK LOANS':
        'LOANSPAYABLETOBANKCURRENT',

    'SHORT TERM BORROWINGS':
        'SHORTTERMBORROWINGS',

    'SHORT TERM BORROWINGS AND CURRENT PORTION OF LONG TERM DEBT':
        'DEBTCURRENT',

    'SHORT TERM BORROWINGS AND FHLB ADVANCES':
        'OTHERSHORTTERMBORROWINGS',

    'SHORT TERM BORROWINGS COMMERCIAL PAPER':
        'COMMERCIALPAPER',

    'SHORT TERM DEBT':
        'SHORTTERMBORROWINGS',

    'SHORT TERM DEBT AND CURRENT MATURITIES OF LONG TERM DEBT':
        'DEBTCURRENT',

    'SHORT TERM DEBT AND CURRENT PORTION OF LONG TERM DEBT':
        'DEBTCURRENT',

    'SHORT TERM DEBT FINANCINGS NET':
        'SHORTTERMBORROWINGS',

    'SHORT TERM DEBT INCLUDING CURRENT PORTION OF LONG TERM DEBT':
        'DEBTCURRENT',

    'SHORT TERM LOANS':
        'LOANSPAYABLECURRENT',

    'SHORT TERM NOTES':
        'NOTESPAYABLECURRENT',

    'SHORT TERM NOTES PAYABLE':
        'NOTESPAYABLECURRENT',

    'SUBORDINATED LONG TERM DEBT':
        'SUBORDINATEDLONGTERMDEBT',

    'TERM LOANS AND SHORT TERM DEBT':
        'SHORTTERMBORROWINGS',

    'TOTAL CURRENT LIABILITIES':
        'LIABILITIESCURRENT',

    'TOTAL LIABILITIES':
        'LIABILITIESNONCURRENT',

    'TOTAL LIABILITIES ASSUMED':
        'LIABILITIESNONCURRENT',

    'TOTAL LIABILITIES AT FAIR VALUE':
        'LIABILITIESNONCURRENT',

    'TOTAL LIABILITIES MEASURED AT FAIR VALUE':
        'LIABILITIESNONCURRENT',

    'TOTAL LONG TERM DEBT':
        'LONGTERMDEBTNONCURRENT',

    'TOTAL LONG TERM LIABILITIES':
        'LIABILITIESNONCURRENT',

    'TOTAL NON CURRENT LIABILITIES':
        'LIABILITIESNONCURRENT',

    'TOTAL SHORT TERM BORROWINGS':
        'SHORTTERMBORROWINGS',

    'TRADE ACCOUNTS PAYABLE':
        'ACCOUNTSPAYABLETRADECURRENT'

}

RAW_PHRASES = list(RAW_TO_GAAP.keys())

# compute trigram sets for phrases
RAW_PHRASE_GRAMS = [set(nltk.ngrams(w, n=3)) for w in RAW_PHRASES]
